Sentimate analysis of twitter comment using NLP

In [60]:
import pandas as pd

In [61]:
train = pd.read_csv(r'F:\VIPIN\Data science\Python\SentimateAnalysis.csv')

Reading data 

In [62]:
train.head(10)

id  label                                              tweet
0   1      0  #fingerprint #Pregnancy Test https://goo.gl/h1...
1   2      0  Finally a transparant silicon case ^^ Thanks t...
2   3      0  We love this! Would you go? #talk #makememorie...
3   4      0  I'm wired I know I'm George I was made that wa...
4   5      1  What amazing service! Apple won't even talk to...
5   6      1  iPhone software update fucked up my phone big ...
6   7      0  Happy for us .. #instapic #instadaily #us #son...
7   8      0  New Type C charger cable #UK http://www.ebay.c...
8   9      0  Bout to go shopping again listening to music #...
9  10      0  Photo: #fun #selfie #pool #water #sony #camera...

For now we dont need label column so lets drop is

In [63]:
tweet = train.drop('label', axis = 1)

In [64]:
tweet.shape

(7920, 2)

In [65]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

In [66]:
column = tweet['tweet']
column

0       #fingerprint #Pregnancy Test https://goo.gl/h1...
1       Finally a transparant silicon case ^^ Thanks t...
2       We love this! Would you go? #talk #makememorie...
3       I'm wired I know I'm George I was made that wa...
4       What amazing service! Apple won't even talk to...
                              ...                        
7915    Live out loud #lol #liveoutloud #selfie #smile...
7916    We would like to wish you an amazing day! Make...
7917    Helping my lovely 90 year old neighbor with he...
7918    Finally got my #smart #pocket #wifi stay conne...
7919    Apple Barcelona!!! #Apple #Store #BCN #Barcelo...
Name: tweet, Length: 7920, dtype: object

In [67]:
ps = PorterStemmer()
corpus=[]

Preprocessing data

In [68]:
for i in range(0, len(tweet)):
    review = re.sub('[^a-zA-Z]', ' ', tweet['tweet'][i])
    
    review = review.lower()

    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    
    review = ' '.join(review)
    
    corpus.append(review)    

In [69]:
corpus[1]

'final transpar silicon case thank uncl yay soni xperia sonyexperia http instagram com p yget jc jm'

Above we can see that all the special characters are removed and all comments are in lower case 

Lets import counter vectorizer for bag of words

In [70]:
from sklearn.feature_extraction.text import CountVectorizer

In [71]:
cv = CountVectorizer()
x = cv.fit_transform(corpus).toarray()

In [72]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [73]:
y=train['label']

In [74]:
y.shape

(7920,)

In [75]:
from sklearn.model_selection import train_test_split

In [76]:
xtr, xts, ytr, yts = train_test_split(x,y, test_size = 0.33)

In [77]:
from sklearn.naive_bayes import MultinomialNB, GaussianNB, BernoulliNB
from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np

In [78]:
mb = MultinomialNB()
mb.fit(xtr, ytr)
y_pred = mb.predict(xts)
accuracy = accuracy_score(yts, y_pred)
print("accuracy : ", accuracy )
confusion_matrix(yts, y_pred)

accuracy :  0.9001530221882172


array([[1765,  169],
       [  92,  588]], dtype=int64)

In [79]:
gb = GaussianNB()
gb.fit(xtr, ytr)
y_pred1 = gb.predict(xts)
accuracy = accuracy_score(yts, y_pred1)
print("accuracy : ", accuracy )
confusion_matrix(yts, y_pred1)

accuracy :  0.8075745983167559


array([[1629,  305],
       [ 198,  482]], dtype=int64)

In [80]:
bb = BernoulliNB()
bb.fit(xtr, ytr)
y_pred2 = bb.predict(xts)
accuracy = accuracy_score(yts, y_pred2)
print("accuracy : ", accuracy)
confusion_matrix(yts, y_pred2)

accuracy :  0.8810252486610558


array([[1814,  120],
       [ 191,  489]], dtype=int64)

In [81]:
from sklearn.linear_model import PassiveAggressiveClassifier, LogisticRegression

In [82]:
pac = PassiveAggressiveClassifier()
pac.fit(xtr, ytr)
ypred = pac.predict(xts)
accuracy = accuracy_score(yts, ypred)
print("accuracy : ", accuracy )
confusion_matrix(yts, ypred)

accuracy :  0.8592195868400918


array([[1753,  181],
       [ 187,  493]], dtype=int64)

In [83]:
log = LogisticRegression()
log.fit(xtr, ytr)
ypre = log.predict(xts)
accuracy = accuracy_score(yts, ypre)
print("accuracy : ", accuracy )
confusion_matrix(yts, ypre)

accuracy :  0.8852333588370314


array([[1782,  152],
       [ 148,  532]], dtype=int64)